name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run prebuild
      - name: Publish if version has been updated
        uses: intrueder/npm-publish@master
        with:
          commit_message_pattern: "^Release (\\S+)"
          npm_token: ${{secrets.NPM_AUTH_TOKEN}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
